---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    CF_API_TOKEN: AgCo8VZQguYxYib5QHwXJFqQ0U+DBgvulZwh0WaJdZg1KQS0Av7flWW8E7lfU+BTWhqYMC5Fn5RE75WQHB/ZDAcWbHf0YQaHZLw+OFyIfxwetKj44UIF7A5EIqy6jlgxxJHM1/aUmcTJeQ0HomZcEOtS2EYDfXaSdK6CgVimFEl+topF7epQlFnQqU/1mOwM7MeYHwuXR2TdsxkbZsW/YGPVougZ59QDkpI9BNRnEaCLNPqRHKFAU0AaBAuXH1/F7VTNnU2XRy8T7QYUmBbCL/LRx3PztxbEVqmnO1s+KAehU0WzvdSmDVzcvSCCU7/bhIRm1DQJMSe+JngCkjXapwo8hEwWMCYu1rA74tcRoYL43lI9cKwxF4e/6tKZVlJi//eUL/kCxDJBFTvOpybNY0RT0WM8GiVgwCRr4avZQ1ylPFMp/NWAk8HnUvZaAltqmRSodGVIxY0aK595+DvhpRgAM4ZTF9dmGFICrBYoHN3CE2jugQRz3kut8FDNkgrCnh1UHhYs9ciuyWz4pwUcfZIhEcBcYV1BmjEBivQasM6MjZ39KjY2YDuM0Hcbs1RktkVMYbWFPB1BiJsLFi88Xn78RgNWsQsm5D5W4EMh/QfcQ1l9Nrbmq89xLQ6QX3w0jjmM8rOJvOvKc/nK+Hwmz9q77SdZAhcSrTFX7rt4KxIcqeDwi0WEz1ALubkwPGUAXh0G7bxEopegb1kSwE495Oo5Lxj1zzP2vNkKaK4s0gG2JFTQI4VdaPev
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
