---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitmagnet-secrets
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCl+kh+kn95clrRQDcQHEm3GC0Ubd0MkuK+MTVJ+3InEIbJLOipsnOhxIXpOPWjkGl8uxEOc6sEgI5HUK36ckvmzMtnX5HfFy1XfR4K1HKpTOn2tk5nMkuKr535rwkrzciXuOU1s6NY9/vHi3LL0tFGN1QKims3/nv0hMv0gv4+ssXmNOqU2LMO0/hQyOe0iUwxP1D8fDfBsLlbCcPNRjAgNUWWq1VvXtnC5tm6wg4YLhj0hwWgkALaRDG3pHA/E69D7A5REidwNMqjBaVYxW03GgF4vo+RPy5RWMJAqe1T+E9Ppb1nJa5e4twBB/EnMuMkKtZMRb1tAIc30hnTvBrVyouzi1M4QyCoeUvijL43PWWruE+BPwg0FmGQCdHTYm5x9KhNHT4V25/dUC9R9uUei2D1UTl3o8NdUD9axSAs76JE7hKclols3iG7Yr3ESWwNLuvSeBGQz0CwGVTSLjSP1AwoIxsy75TA2NF7vSGAx56zMRFalojXdR+WriDgoQ8JgJLllIZ4j0hk+Kmw02smrY89bZEQKDMo74y7Vr0PMNkaYr530Qr7YW8wJuu0juxatDEmbNXKxT4r47XsdH9BYQONzSn/Df/nmwa4xxzXq7/2OO2CbLMwdu6us6ECNw4TmmWBQrQ5gcyb2t9HvitOKWCQZqZQn4HCSzf07pCXjnnwlDEcTWPhEmFUEN6SyF7TePICIzH10wCu/ps0Wu5zcjUdKkYgRgz6rA8zUqN2vwuOEPeBUIcHTLhmE7bP2/Q=
    TMDB_API_KEY: AgCoLcZkSXfjTcI/oO55OqjTZlXsG1l991F2fS+ZixiUXMGYdKDCv2MucZ1j3oF8xaG41Pfd0EnUAfrlV79WMNj5AttsJhBbUv8Kc0ft/bUvjJF37vw31tqX3vWEZN4o5ypYF2GBY7jfJMqrj+njlXCn9ydN/YftmsiSozpsizLM08xuXiUIk0NwAQ73tH23bLDIgE6zUfR2kmMuDD3JeeuIy1j393xFLHzZB2vmKfvXBafpPIt/y74JrXM/lzl5hWwiXUm5fFi240D5t99J6H41G/pxp0/84Oe7/ziy0Re+723nplbKiynlB0xlKZG3L7DqEmf8yvev0/u+bqxUZfjZ6ZE28klIYNwjvGw1Cd9J27GCTDaabMkdD8+8HmZkMIgDrpL8YY83g8k1JbFx7kFBgzXtaAzVsU2/nDAueW/6tVfp63YsSbUokY2vwkR/uV0aDUJ4nEGN0Li0iLL2bP5/WYCCxzjMzGNuev/zlddzxFyAll1XSair4CWQMHYVxlIcK/zo7V0oROmQhZC6Efdt0ke2e604ndygJHZRxOUhVCcneCGV3W+voXpwZ7jYPcEO15VRahJl1vKQOQb0LH16FvTyANE2gVPyxAzXLkoSWC9ve9Ygzn1jQn1WMQqI0D5IAsJH3S6F2Kr7OqPG0l2Bqr5usXQJriF8+JK4fPg4oQJRbNUQYtHaEouHK5vYr/OlIOaaCLcoKmfVMMywyhde4LspjzNicRGLMK/8Ki/O4A==
  template:
    metadata:
      name: bitmagnet-secrets
      namespace: apps
    type: Opaque
