---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bitmagnet-secrets
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCUc8Y9MSoVZdcBxSFhnEIWbUlCouIwQln98+8OSMkodi86EgnHC27IP1GkvAgMIPFWvUQF+JithjILGLDbpnpff4DGkPL48XHUmhG2g6M9yGfGFJlF/vYnyn6FHOzWAPBXVxqS6LDjK/hHzHhP0JyLYPWkiIfqHvabpwysagcPz8nVzkhAk83FbINnJWtCcq5EgHsrzdQHhh+mi4dsIvHJ9tEXgJQw1yTZlUSfxb8RHhioVsp6WalbIDbS5TBOXyUX6BzoTE9Lvg0Zu+g/Dgq4kYlgFXXRd6zXr2KcgBqEoIfsevxsi/sIXccEy6aJ2hWknpqYMPCNVSk6QP2DvjzS4LPa8avPiRompulKJqpok9FOmeM4zyC5XGsS8qyOdXefFeQZW4WOjmfhAmFlw/GeZCzunH/jxGWetwoSHdbCE8Osw8IEN2h/fgK9ifhKONa03XMNAm2vx8kR2Ozm97guMf5g86b6yn+n/OHFFF1HYcoMmH2ULMLtWJBlYykPx/Q5AwzTpx8bsjuYN1wdLT14tSchNGdNbj/m8Y3WIBQ6lR3wOSVzq4X2yJCKIyVO4GDnMtdgT3RwJ9OqOAmWQrLSQJrsS54eC8GQpSnnEi/fzpXYXweCP2qZ1KLsOw18AYGVW+3bkrX0tdE+GNBA7leBNUuTR4w68smAsXfv42rvqSc7EYL5oBe7ge/GfYeWKtMR7drBUhb6ckBAcIeRuWLH4U+fD7oPXBH7uBl9a9I3lPesCaAsCz5SmIASoRRmB8g=
    TMDB_API_KEY: AgCoLcZkSXfjTcI/oO55OqjTZlXsG1l991F2fS+ZixiUXMGYdKDCv2MucZ1j3oF8xaG41Pfd0EnUAfrlV79WMNj5AttsJhBbUv8Kc0ft/bUvjJF37vw31tqX3vWEZN4o5ypYF2GBY7jfJMqrj+njlXCn9ydN/YftmsiSozpsizLM08xuXiUIk0NwAQ73tH23bLDIgE6zUfR2kmMuDD3JeeuIy1j393xFLHzZB2vmKfvXBafpPIt/y74JrXM/lzl5hWwiXUm5fFi240D5t99J6H41G/pxp0/84Oe7/ziy0Re+723nplbKiynlB0xlKZG3L7DqEmf8yvev0/u+bqxUZfjZ6ZE28klIYNwjvGw1Cd9J27GCTDaabMkdD8+8HmZkMIgDrpL8YY83g8k1JbFx7kFBgzXtaAzVsU2/nDAueW/6tVfp63YsSbUokY2vwkR/uV0aDUJ4nEGN0Li0iLL2bP5/WYCCxzjMzGNuev/zlddzxFyAll1XSair4CWQMHYVxlIcK/zo7V0oROmQhZC6Efdt0ke2e604ndygJHZRxOUhVCcneCGV3W+voXpwZ7jYPcEO15VRahJl1vKQOQb0LH16FvTyANE2gVPyxAzXLkoSWC9ve9Ygzn1jQn1WMQqI0D5IAsJH3S6F2Kr7OqPG0l2Bqr5usXQJriF8+JK4fPg4oQJRbNUQYtHaEouHK5vYr/OlIOaaCLcoKmfVMMywyhde4LspjzNicRGLMK/8Ki/O4A==
  template:
    metadata:
      name: bitmagnet-secrets
      namespace: apps
    type: Opaque
