---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-db
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAgp1rnRevmkWEIH1PwHuFZPJ59G3mtjAR+6AjZMcapNlzzKswJyLC67sgXKytbJNXd45OTXcsnVb1VvKask4+OV5myDyA8RxtpqDAUzu+GtxuTBpg0KWvodoblqFBzlOztvO1c9GWWCYZcKVWACrxqYs+iga4L21Cd6Rlr96ko1PeRUCV2iJYQxJLRK0ZlaFN+WZOuUXCrrPpj77cwvfwl7QRIRI9Z2ChX01lDSVlH1MwwUUE3MlrU83Uv/dml/m7Pdlz685qNIMkU1CNEh+tAPlsFSkfi/q673F0bXhYWPDQf+p50muzK29mtZd+dErzUvCrR4bvcNoPmBNBAKQJjRkeJqlDKFbmLpnUnX5t2t+TfdN3DUqbn2mfNiAAnyAzSB0ZJCBATwYzPJXsZMd9mjBdCJsGUnUKDvyIIHwDJXwXCzYuldqTkD+mPyGmMjXbd26iZB8ZSmJONeUK64KX8p+CVnsTMdyriVnQfFjaze2wzOhhViSnoZlUSyfb5fcyZRb7rCH1Qmclqv+uIphgQaO5B2lOexUytHHpPrcef/kk6ZcmepKNmDuQShVrV/68itbU7HZSNjiB0+r0UJ6+LzyK6weUIF8I9jk5CuMWQBVhYH0Ej/JXC9PkIKYX6n1EiVOUA1WwqrggMcx02XKbbKCu7AASr5wc90KsBwAqSyBEOuWyxxZM1dXVmDtne+QyULAanITKR9A==
  template:
    metadata:
      name: prowlarr-db
      namespace: apps
    type: Opaque
