---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-db
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCQ/sO9OF8kYvjL4BpCDWt8NwmBd9x0nQzK2MqUv7XcifG0qTC7F/Idl/agOMTowyzKmt6oNVBsECbroRZ8PgzVRY7p/TwPi6vDPrQYvyOdGFTtJwXBDDbEyWX2+aq+bteDzq/axb+wkJE73OdTb7BPuLSzfYjFVuCJv3uduZXwhA67hNLiCAovpo0vnKIhOS9iODQzY8soXxrJKnpbUiCVaUqtPWOor/giHqw0UidYHwiaRP9GlJaQcSNA0auwTkJ+K0rFlR/jJe+Muvw029y0qQtAYyZX/BHR8xjqlbxyak+CoPkv5VHeBs4FscjAY7W5IT+eWFCS2s1GnCnYPtupGBX6DCJA82Lipk+sBd/2lJBw8lQ29UIWNtG0TjdUDS4IP/y2R3HzlbwFVMLo6QmH+rBal4xfb3YFlNhFKKx+pzpcdUhTdHTdIaZzJUvQI+FYMMpVTkQDiJ83tiI5caoc9zoJSycTgIBc5uEm6qzi1zECH9eL/SxkWF/QBwGRa+//5qaQktOHbckXrrxUguVsfKxX069pELINe66VPmYRMQE8x2ax7IO5h+npCdGXg5ogXVOMj0OL/Yh+b6jnqf0txUkAzjBqsNokihzSnIvHBsYbV0hDIL2oAIRENtjhiywvaaNlM+ruyFOBowLE6IlEvehlDUaS9Hg8OO73bj6IaeOET51Fps3JwkRZK0AJvErbpNPlxmyrwEEo+AqyfkfE46or0Ts75lNdTjnGSzilNg==
  template:
    metadata:
      name: paperless-db
      namespace: apps
