---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: avs-config
  namespace: apps
spec:
  encryptedData:
    config.json: AgAWLWx2lxmkUQYFIv6/DJKeMENOfao1s6ZSHg7cajDOJf/bjEbMzPhxhpYtD975/LopfAOdNwG1dvzcfMfATWknjsUgE3Kn4zJfWQ7uo6AZ8E6X5XyJ+dakMiP/GdOUFjBH76Ys3MJNa7gTf7OuVc4gxzWQYZLHmZHWyjYHwZMes3XS363vQAI1c2IB/n4NVp/TWaQI7ZBYVRrQnYCdvkrtIj/ldh8JQmkE58rFdbE7xjEUuYn67Sskk3N2cTLo8zyBCB2bQ4haih4f0qZ9nr+Ja0CrZkl/9GAmUUwX8ti/pqfkHMPux7CPn6nbWph2ZNozj1PvvZlDERAahoPPBUMk8un36sWMnOAAg6z43kH9O2APRKeVNIBWoAf0FFIM9/mN7HarRtWu30wiG3YmxK7V2z2Kp9sBfz4TIBmc6U7Lz7j3yR82Uunk2kT8t1QDddV4oFAmXTPIe2m+/AYqxiECg8ZK4cmy5WiWwKDwf+QKNKzimiToX7IKlnv/n3qctO7XBr3QdyLAbkbPwA9NIUbsQr9AZevgporZ/JekKc1k0P0EnCYpNoCJa+VQ7NoQzosunbxtnOswGWSG6xGbLGVPgxRSN5vp21RFxrWNxLfM9aHNyPIqA368tnfMH2T/vngMMoUZFlK+xRqcS63+TrxHO3C1dl1QOHIc4D6XtW6sFIEFY1OP63IMt/LnsqE7zNgQYz2rGkfsbPWDoW7Wc6Fdut3NWWQlPbqSpvsm5GnqOuzmySZoqtGOVQ23nH2fgmdBmZXWrTT/Iqnde/YNsXo+RSY73MEUlVFrZCOe4spbT/s9u1oMJi9Y9TxHuLErpqFGfAZ8IXg91ZWfBBFwlqZQC/KK5U+8V3ApqbWkpncKv2SNarm14ShnpnZKKNfyAIddQYdzA63QrvxopPfRl4amqXVtp0p6aIcUNjoP8a+TRdC5xlqR2Zox1mkQC5q6lFaB5kgabZizIBa/AWE=
  template:
    metadata:
      name: avs-config
      namespace: apps
    type: Opaque
