services:
  nzbdav: 
    image: nzbdav/nzbdav:alpha
    container_name: nzbdav
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - 3000
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbdav.rule=Host(`${NZBDAV_HOSTNAME?}`)"
      - "traefik.http.routers.nzbdav.entrypoints=websecure"
      - "traefik.http.routers.nzbdav.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nzbdav.middlewares=authelia@docker"
    volumes:
      - ./config:/config
    profiles:
      - nzbdav
      - all