services:
  honey:
    image: ghcr.io/dani3l0/honey:latest@sha256:0af531af34ec047d72ecbbbb4627b8b45039835755c10338f6e2428ee23e7dd5
    container_name: honey
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: $PUID:$PGID
    volumes:
      - ./config.json:/app/dist/config/config.json
      - ${DOCKER_DATA_DIR}/honey:/app/dist/img/custom # place any images in this folder, and use custom/image_name.jpg in the config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.honey.rule=Host(`${HONEY_HOSTNAME?}`)"
      - "traefik.http.routers.honey.entrypoints=websecure"
      - "traefik.http.routers.honey.tls.certresolver=letsencrypt"
      - "traefik.http.routers.honey.middlewares=authelia@docker"
      - "traefik.http.services.honey.loadbalancer.server.port=4173"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4173/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - honey
      - all
