---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aiostreams-db
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgByMtQ0fPeNiofCD7e5TIUrEPDSz2ubosg3/9rzxIBTVnk8N/SdomW6NJrYIIays/pI2p36hscMA9GIcsfkFstcNDphX3rvf65mrWYOdV9E/8/fYS32fV/Gfj0x6YpERQA1zdAKO7pj6g7vkjDUeNf/DWw0jrlvq6HhaJAaZwqDJuJE7YtVM4zyOA9T+rcCz8CSQ6CS3xRXfbBXOlvJpmENoCeQss2Co03/HWLmwOaChyBfyNi98YuVZwremcmGt6Q9e3uKyEP05axcqW3t4H+0et+boNdnzuwXmeDRGm4bV/KYV2wZYKjUViruoLwxZsHPjxA7BMx+/b23d6rtCmuecXz3C+PImClnOClQQsshLiYc3JmTodN7lLg/eR3WgoC3EiqytowGg1sIJ3Fsqjwav8M4SHoG3HXLV42lHun+wQ/RTzYyiLznFmakglSR2HPa48BA9po5GaC2gnJovKSet20nrwdlr6XCLgrVW6FEEyXly4pFpOssnzD8U9o1cd62Kg+E39u6nVEtFCs6w/x7skkzPzaoQNEZNZXHwgciaW/0K/nCUuBA2ktJZe4KSaU5M2nOcqdA+ALXHGpTMrZckrQoaA3wacHZqq6Nkrg7uyzudIzjUcXtUf+UOjStxqrdqlojAeaetzvJM26QF86wfvAa50VvWlllxp6NPTBhXwW6MYEHu54t3O+Lnzpt9Ks2E3Toda7fml8p7bDVu2eH4qjzPI17cLhRYLLwMb4qBFgfHyZTpB96U87pPRiBUZ4=
  template:
    metadata:
      name: aiostreams-db
      namespace: apps
    type: Opaque
