---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aiostreams-db
  namespace: apps
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCT4PrPosWqWLEAxuU3YEkIbMjRln/ARUkVCUycmVXoJbjFewzKRUEhGSuqQ0L3E+u7aZX4HsV+5KPe2FWtM267BEx3Zd7acQMR3talnvtKax43HgaVESLcOAi3lDfnZhye9NcgimOXk/xbvfu7qdr+3/Mqp03mK8OVvrDHX/rJjMrbVu4q6NbMi31a7VZZwOF5HcZjsIGKIx0/UnqeWhtZ6rJl9f/6jDqvhNFv/5B8AUlNH70Oe1wMl+4/F1xTY9ItWP5T3Z2sfPpHZcJGPd6LfNp3T86UENNOX6AJlEgNRJCygyarXkaFMrzft648kUU4rLOQlozQUl4pKgBzwC2e1PCamoOurtAKGriIhPOQixoYovg+cjV5N+/LWOfmojfgNFhoWcOYQtIoR2FLHt+wcZEXkPD1xE0O+NVNqMBHtHatlZZN9NT7Kg24jzZ6KInPKpdUvjRF2uCGTl77BKvtG+Ha3insPnIWarO3D4QIpvc+EQzkSw40TYQDgBBrpeYES9TfEjzme6EfIgcaoFfWhQzIYdgo2oihN+joJNvk93u78rNSVwfYB2tCJvh6n2f3Ws10RPdSnZowStADPGco+WrQScKXVEs3Jc8I6vsCAYTS6lwxMMRpDbbYmz+t+NT7OAUXRzsNaRKmx/h7Bka9mevC3ewnlcP/Ze4Nx1ALxU55eeE+v3QRhTwI0u+elQWAM5mUla0eBTomKAJCUPVTCX7rsa6wX0SXBXhGl3G3rNvyf5BMl6LWcx+zCaMrX3o=
  template:
    metadata:
      name: aiostreams-db
      namespace: apps
    type: Opaque
