---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    admin-password: AgB/9KwlN/4imi/lxe+r9bq1LA68t8nKzGKWUexDqZ2z+R28/tm+tdobdFg2vnwuCnmWFnx+4gjBD1XR5mEfqQZBzoCRkr3Nd6vhhQ5d14qGy1PbwWUOYP6L6fcNOVfrV4wAwP1dgMS27/8EOZU7LBKA+5w1py6vGvrILsdiytuOQ7tbseL2BfwoTDxJ7q1eIZLsqJfadyoaKpc43DPSi/KB5CoREFRCMp92KDNei9eGLM2bsQNiSaokV19xqn+DMcjH+dztqO1LEjZknae9O82Ye4q/75CsCq4fOd5Y4MRSh9m9DdQD4ngpLqsgL9RKLzwdHNVD3WiYykxQp1uA+6GBoxNaAKh8T/JcEDQ/obmpe/GQURsNqyx6XiG0cC681cN+FW5Oah8BlOiXCU75VUEvZBEc3j7tFR0G8mRREDXhcO2vZBFPPZMp0jznS5Mj3ZgEArLiTMP2XIBMrmi4Jb5cWrM/wrscXvx1XSLeN/NmG9BGeYsGI2qaK2BdbBthuTG2YNqm0nZHCIBXTxfMgv7Jzgg5LtTlUkjfTeqAU1Ucrh83sewECDmBxclbXzUwhZKsD/hPz6dSSvhDMpjEFQdTV04w1JB5745Wl1921ipddRhLBxvc3bKNHXiXlcyBeRLbI23nMuOTpeA1VB6PqJ259D0n5M2X2fa1xesWlFD//a2Ly0y8bLRu1RhWnM91AQpjLQgxDy0ewvYsuf9nDi7CWVhpv1FllbmcnI/44iR9tA==
    admin-user: AgA4W55H2hxqmmv7Y9Uow4R6KVoiuAzYWt8paCknG/eM3jw0/o9SAujWxDbcnSTbPa78XcB0FlUBBFhWPm9ndK3v8S9PsIMAlnvNJQ6flNk0KOFqyB+wWUIEziMQiNl5esit98nhNnikXGCZO/HSRdDUTJVNT8JFrWj7ni5CEzg9q04tFq+0KvK/YzJar+Lbq/yjQXmuvop2Jf73J8ZjA66hkIE/mmTTn7ofs1dxx47hxIjYYXFknB1cPxGZyyyxpxCe2ufy2zrYb7EFJVY1+HZ3qBFexWqO/H4IOM8DdGbYfmTP596exUg+Wr2RVbEAcOKKE1Fsm1NkE7Ha90Kjor9pY+pBz8/SdKc3cTpOto7N/MjAxGx8rBLc27ncw/Psmt1DXgeYVIQC0eXW2tjqpH9Z5GRcLXra6E+OqFtD7Pgf0Ax0JTr4d9z7qX/G/TxRCFtPNFSt2PBauuKhOGO9HkTqrvC+cVW5+mh2C9CwPtb6RzOu6X35YTDOhKWQwOdLO10bYmldvAtUv3i+n3DyWSlZkC4intRKq7hbAAKWrq66Hg+y4bw+gjIv3JdsJp57CtmLimMonY8so4Hfh4pJVUiRYgwwo0BuL9npPK13uOvfXBS8356vUvdKXIikQHIIADfs77L/jisb8TngcHujopwYLjXIT+2TtKEyeISRmHl9zdJ7HegBR7k8LafYnLNAlQos7N6WuA==
  template:
    type: Opaque
