---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-ntfy
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    NTFY_TOKEN: AgBX3c5Q7xl6MirQBMITbx2fzwOqJ4gKu7jKPkA1OyAUwOiTudnuObUTh1Ub1o0X7DlKqQCQBJ/TVEkHgMuD08giRckaTi4pwR0wXcduYRqGFGmJyAJ+AnN899ESSi45rsPyoYGhin7exAFI9TORUiBHQIEMVggZ4Ejo9XwvVvXTT54PFgsYY73ntTLeOGXgC+JvfvvN4PpT+jb2IsdfFoVVFGcvWYso9d4EJgRmztY8W8OuzHXD+YHQzIg5iAUmSZWmqYAd+Re3+DviMsjgbJgh7EUZbt7owyHp7QEUYODT0ciUpfg5XMJkw83h5V78xmXkAdLX4vTFyKiOhZJkPsJf0yFwmzok/bWFgBi4tPksZ6zdArUeELBcnGA45MxML7E2M7NDgYb6UGCJaRuqrxc8hg+f/WquL7cJv7Ruh6zzz2pxvv+51oGc4pSd+xqZVcRw45ND61PEQ5v1KIAcSQf04FJkxkvTAMvjWZd2RQyp2AUFvT6C82mvneOSqUH1xFIxHMJ09RCPhqv5xuiMdza2ISoupUnRkKQrgeKq234Esvh3YAac5GYogkcAi0Z3yvpavvgCFReva58atFS3995ZeO7KzDauaqqC0UnPZq2jIi0c4RySrUJECv3YYAnTk3fGtaU0ns7FDk5z1TyVm1NoWvwWFVzvL7NW0k5yAMfbXWbNEudTGOupdDNG1GZgw99A5EckGLduc0Frvm4a6DmeLZY7FVUGJhGH
  template:
    type: Opaque
