---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stack-audit-grafana-token
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    token: AgALR/WVd4MNg2CnlUs5iYoVn4JK7QTCP56JljsLZytcUOtHrL5wjdlz4GW9SV9eHHjVAb8W63uCJFVicMCOmx1H9JdUD0vTkVTF7uxCpHsRoRdrEi2++/yIoXOgXFbcgcdwR5dBanf14qkxD6mgCPQHPPd3lSW4/g7zFx+y/T8h2Cv1vwKKGowk9TQvzNqYdggt4ulB1IcpnFHaCqykjLeKw7XqUWE8QMV9pDs1JYa2LttVjUZ7J+5SlAhtBMKo6Lkm5acCKnPNpmqojaroLl72q9/syyjQYRTxNBcXu4ykeyQBFlY2HE7YMBjwoF5193w3fEiwQ/uh+C5Zp3oa1XtSJKVePxK8zu6ALvQNBBpx1Fap0FlFJAH2iCh34N1UR3iS2wnkIo9WsEyXw9XviPaX1PCddgw3l9Pbp25FhV7DkHL8wZB6do7QkcjWK9M6H6p7b18mA3d+xX6hMUfhXsy8Sm0qnYMWhQBTL82OLI3/Z5LtCcSn7OQNLWQfBQicxd76io6eEM10x8JBgKSc0iVa5AAAMgrmUKNrtRLfbSMgXEsH3r1QzIiwepeq3U4e7iQQ4X6aBKj9VVHwUPvoC2sXOUbTI6f502RZW5/uLbNNnKlk0SXgeUQB4OPXQt/4BEu4DF1kEG3je3mNJIYY4ymefISj7vue5QEHhYZbN4cJ8Kh+25W2XlahHayQaTNp897imqHvoj47dq6yR+jnVadt1zEi5LBl6YU9ypsLtPQXonYbIuwLXVzMvR1HZdFH
  template:
    metadata:
      name: stack-audit-grafana-token
      namespace: observability
