---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediafusion-config
  namespace: apps
  labels:
    app: mediafusion
data:
  BACKGROUND_SEARCH_INTERVAL_HOURS: '24'
  BT4G_IMMEDIATE_MAX_PROCESS: '30'
  BT4G_IMMEDIATE_MAX_PROCESS_TIME: '30'
  BT4G_SEARCH_INTERVAL_HOUR: '18'
  BT4G_SEARCH_TIMEOUT: '30'
  BT4G_URL: https://bt4gprx.com
  CONTACT_EMAIL: admin@example.com
  DB_MAX_CONNECTIONS: '50'
  DISABLE_ALL_SCHEDULER: 'true'
  ENABLE_RATE_LIMIT: 'False'
  FLARESOLVERR_URL: http://flaresolverr:8191
  GUNICORN_MAX_REQUESTS: '10000'
  GUNICORN_MAX_REQUESTS_JITTER: '5000'
  GUNICORN_TIMEOUT: '20'
  GUNICORN_WORKERS: '4'
  HOST_URL: https://mediafusion.my-blue-car.work
  IS_SCRAP_FROM_BT4G: 'true'
  IS_SCRAP_FROM_JACKETT: 'False'
  IS_SCRAP_FROM_MEDIAFUSION: 'False'
  IS_SCRAP_FROM_PROWLARR: 'True'
  IS_SCRAP_FROM_PUBLIC_USENET_INDEXERS: 'False'
  IS_SCRAP_FROM_TORRENTIO: 'False'
  IS_SCRAP_FROM_YTS: 'True'
  IS_SCRAP_FROM_ZILEAN: 'True'
  JACKETT_FEED_SCRAPE_INTERVAL_HOUR: '1'
  JACKETT_IMMEDIATE_MAX_PROCESS: '30'
  JACKETT_IMMEDIATE_MAX_PROCESS_TIME: '30'
  JACKETT_LIVE_TITLE_SEARCH: 'false'
  JACKETT_SEARCH_INTERVAL_HOUR: '24'
  LOGGING_LEVEL: INFO
  MEDIAFUSION_SEARCH_INTERVAL_DAYS: '1'
  MEDIAFUSION_URL: https://mediafusionfortheweebs.midnightignite.me
  METADATA_PRIMARY_SOURCE: tmdb
  META_CACHE_TTL: '3600'
  POSTER_HOST_URL: https://mediafusion.my-blue-car.work
  PROWLARR_FEED_SCRAPE_INTERVAL_HOUR: '2'
  PROWLARR_IMMEDIATE_MAX_PROCESS: '30'
  PROWLARR_IMMEDIATE_MAX_PROCESS_TIME: '30'
  PROWLARR_LIVE_TITLE_SEARCH: 'false'
  PROWLARR_SEARCH_INTERVAL_HOUR: '24'
  PROWLARR_URL: http://prowlarr:9696
  REDIS_URL: redis://mediafusion-redis:6379
  SCRAPE_WITH_AKA_TITLES: 'False'
  STARTUP_MIGRATE_ONLY: 'false'
  STORE_STREMTHRU_MAGNET_CACHE: 'True'
  STREAM_RAW_REDIS_CACHE_TTL_SECONDS: '3600'
  TAMILMV_SCHEDULER_CRONTAB: 13 */8 * * *
  TAMILULTRA_SCHEDULER_CRONTAB: 33 */8 * * *
  TAMIL_BLASTERS_SCHEDULER_CRONTAB: 20 */8 * * *
  TASKIQ_SINGLE_WORKER_MODE: 'true'
  TORRENTIO_SEARCH_INTERVAL_DAYS: '1'
  TORRENTIO_URL: https://torrentio.strem.fun
  ZILEAN_SEARCH_INTERVAL_HOUR: '1'
  ZILEAN_URL: http://zilean:8181
