---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB6Fgb2LarGIikEVgFG5jhAv3GJe0w2kkPpUD0TRIhbTRFMpQsf+JT08Xw2mcdqFCutb3pLQMEUeP8tfIMSIVecxdIt2663RRHws+Oe0zyJtG6nwDz4pJRXESToZzN3+wJi6BVyKRJ/sUmrkT9pfa6VvLtRX78m64vCnOUJabPyT6yLDUuNSpDA6IuVwJhKXsgstH05tX6Bjon1L9+oH0ScyQxB/rOdvGsYWUOkpL2UZifzYzjIrVv7TGtAU1ciONiGv36uRYbmNItslq9dHYcpjl6ZukF119kfjtMygaNhEwOuCdExquEjxCiWKO1/E8aYARddpmi4WsYgH8Hcjy3YQBBN5JNo5/ndhHqEa9hakkyoaJZm54uWIOnuLU9Ay8oxZdhtn3n7B2mSasHPFQjHscSuLaLaPZihlRxOGnfo9VD2vkxyzBLuHWABprX/rwxSQVb7afn9uEhaR6up4cVbS7lzAql0HsvbzFTuzQnxZ5Gw/+TjRvvERGFrH0Zw7sgnMMmpL+vUfDGY4x7pPrp1PRqpeBopEWRG4N7B7LsqG8DEKABo8nlix4SJtrg26DgMLQ4yDdagqZeJMgjxkVuM+gqIha1R0T4a+SaFFRpkS+qMEshqZmRe54rjnXBsydVwF4fYRE5nfifEVYsFXiHCgE5JmJS5O2dPr/ZsWchj4h3WK723ZutXnYy+0L3kMNrkodwrpnbqV/gcH3z5HZbU9A==
    client_secret: AgBWgvaBTzldaI7g/muDLzL2iyBSKz7pNjIi7yTqHXaAQHk/hGKTXv9aAU9kwuWnrAlRqTTpw3aRNl/dSfpDvZfuETWNwsi8GO2RZ10W0ZVNJ9zVRtkVmUrKArzYUyd32n8Deg4Uf8lsCsmOpkEoq8W3/bKFUSApSIpKYA5hMpyADecAdSbyOvJxmbGCopYPquVI7VHVI9s15cFhG/QS38/r9NpzT0+0CEKktr6AGEFdiirhrTanNt2i0oGeDPIPFNMEFQhSERPrPIKtm0kL1IlgZkDkytf5HfvYi6tVrUvqqW7rNaz1pMpSbwA/eq3dM6oyFzobbqKaK8zAfmH7n4KrTNaA8THKbDzgIlnBuElWq1r12qc+dFDKHeb+fiXvG/4jkNH0apfbDITDpwrsYUlDnzQl2dlakk2QJFJnZGJCSvo0owKzybPzUA8//r4IrgHY3jywa+hpGeD4nCLz66bpWgp8moL3gP432r/ENXGHS7qaSlCIWM40wM22oF/J3yCvIsC1y/4hoA5detTgV36qy6iNnGKwvOy7w/f9dLyG5hd9217walp6GbmZcNSbrJe+DA063vj91re3H7ynyF2TyLu/vTLB3BvxeuXkDU8Rh4ouys9dVmDd+hCvcpzwEjlNyDS3wFfmfU9CyhzTSBBA5Gq1b6wznlWWNqi7slrigIuEBFuCa16/2Axz6js+D6s1wrBYJ7caEycBIC2KHG0uVeaWRNTusBw0/2PvZCaU2ef5JTWpLwCHZQRCXK7i/3fdzEEJGn45Hz778lwRO+N9
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
