---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC+lmNasJtDYPqzlIf7sD7tkfhxI08SQL7l6v6K34BbICZlPWmOvHomba/wYxQ8tFTXbMWBoU9Fk9TE1QN7aHTsLADMGxblIMcB7xq2d2rHcv+0ec+CarW7MRR2Ep/sqfXcVDkj/LmmzVwbVeumK49xUX6tn7SuV70Biijmtc9YZuHI2ReSWzcS09knEamOoiaw0wzZfHt5sjzmk0MqsU/VMn5zO78OT8u8g6DptQo+5V6uSjaLjqj7nWenEhUcx/NghQab+4o/z/59jMUR/NwR2dIIxOArsUWuPU7+TRB+6aB6EpmCHF3lqeu/Wcc6j2K8ZVpg/3XN1Kp5LIca/7fGfLuScKQuzJughVC6XcqslQ1OGKqcWg8QEGziEe5BNS6jc2yIQRr996z+ZfzOufh1ht7senofo+KUVFvTiVzzbdh+peEtE/XXYaAPgfYwf+3U23dGRAPfJ4J8OWQ9nS7pWV7IHVweTv7QHLEHXIMvtKL4rz0hGNQKTEoKCvGjxQ7c+4RUiNP8uRcDvFfb5mbLMLeBfXoJJS3o+2MXsgXD1XAG/1ljkjfeCJkYaHcOv0LkC8q1rVCjfXNN5kJSCcCaiEtbtuCUGoq8YigQVeSzOBsM/BL8XDd8/kN81hTWszAiTsMmYSF8cCkkpbBs3zKcMrkGsZ+LM8rCekyhUq0zXfnPuV3HzNmz9EjWET/BZ/6qVwDOp672W9AtunTCbaKEfw==
    client_secret: AgCj9aogznAUQ9alOrODysoapOO9H2bfzYv55paNDreZjOJmJjYaVFuuygQNHdGI3DK+pGPaHDUaCYvvBHmDHCy8xJwb3irnMDVq0eVTV2rBVAZgCrQap+aASfmUNK/12YmgUvPNmJdDja7FUA5YmsLHYZ6sMfLEY8tZACBM5PsS8WP65tovAaEoO3PeJSqV6HkbsWlxuEFZ0FXqbAzC7WgaHUBC19tR8D+OD6IjXV+pqDzr8v4uYF+TS267KepwhmHtn5sJbjy38pE/32gnrjVWcSh7+CJeeyXBtSCgMnXVX9MWJ6Up2G8ENR22MM+bre4COm8aeovAF0zllZZ5ToTsHRvuOYULYgTpxPCnuQwB4tMKzp1zP7QKnnNwZkLnt5YnQyx/jim4W+p9laD58Rd5/grMo5I5x67CxEc0QJqBZ0FguncYoBJf16FYsOahYdJq8NJjqBiFJFGjs6mJqAOgh60QhMCGI3Rtx3GpFN+7+I51mI7bXCcpf2FEPKJ5onJmvStEzUG3X9v/ltWh+VYBf4tZGvJg/Q99UW3JfJcuyhtYAUha8KLsHpisnWHeXNhqlYSNaDWsiERywGrxLl9rykv8jMuMz8x636NVzniAq89w6GUIlNFx3raPEUuscvZCp6cERRHOliwTyCt1z09MJJR4QF0Ws7wpL4jRLuQK34rTUyICtk2lMOwjx5gm4WIJjzMYKSeCwHjWhp3T+pVXqo01aH0ShfwxeNOweEXswK0RAN3Cx5qnypPqf0mMoo6FzOvcc77baWYjFfZkusAy
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
