---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA4mtZV/Y1xy/ueeZqoRRcKv7Hv6Dfk/TQ6jVZqoZJwCZ3+4OYBnzZQVpCtnwl+2jF8WpjgXwC5gTpeMUq9V3MhZ/tlLeOiG4RKiRpiZjRA7Dj5l8vhIhivg+RwFjdHyTrxP8Ly/3OOy4NWAee8xSiwYr3t/j1x4zVmANVs6mPa6O/9a+yOYcVrh8FKExPre7/H+5c7rtDafhoLJJE9WfkfpUhlN0X7/xui2gwyZJSlZ8KCjJIq48NX+LLS8X3Qp3BdML7yOJb5DEkeSlAOiOGQ0ERRReo2St7//i4soAaprmf/1fxRfbEsdbYwqPcT3Oony6x+dydt4pFL3rLe3dSs2a50sgEyuO3J6tiohBCMZK56nj/evA80U5O82qC3hTCtrTtngqcf2F/6Vc6e5VP482jXilU6f/7Ybj2zBdfMUa6JQd6LRTF1JMcSLDFjzYV6TJSvPmW9oZ1c0MOAVCMyprdOS0OgGyOdyFZf61EhNKjWLwi95dAJJPNTIsoG6AVhH9BVLnvN5eZBbSCzSyFkiCZXPE5WdfaTcz0a1o2vov0HnYRC6HXDV6BYtt8TS0Gxfijw1mQzlFzXOCqaaRDR5LiQUEtOc0UXBZYcHr2sSBK/XUOCVfQbxq/+nZFaIQsAHqj0RmxIHRPIwoV4fgVJJhSWRxG501tigyByM4tz86Ee5ormHgNEsTxdvIarA9TGJk9YNeK1Qp8+zNtPqTOtGg==
    client_secret: AgAzvUWpDMElMn9QgWWXkVDYx2E7MO9oj2yJff5iJwm9Xv78YnfTYtKwNXjwkIpCDNivUQay3nBtAAvsCtNr/8W/8t54XhkasYhr0/gXm6kmmaNH8oag5UJM6QoG8OOD1QMngjrFW10MnKAS6znl/TOW5KrY90lIx4lgfyhOjAeZLp77VufioB8c5hzfWgN9oeIuRRLEFoLZyY1ujIS400Kx9VJsHZj+kk9d9TkaPm3yaL4uv2Kqdi2VD1QUGsE/ybMHOrclk7K013zS98RBXAG+ZihxcJWIaHxPc5MTsbloEp5wwp+7J9ZnFcc0su9+TsXRLWJ6pCSc9Z9hi6FUNeOyN5m1E7KQ20XaeLK26Bp9qDGOM5FmICce2/qD+iaVSRqo5btWzVFE8XfRNWuRKcKBD0J8JDoepZZWCAJUol/RI5pWfC6/XWbAVu5xVbUwnGpFtReUp/NDQGIdSy1JTbfMHA84oW2rJ4AUDGCU8vDTA+OOI273vBAL5UR1LI8FZ/+qqpuzP6j8W+Qfh3Z+bPMCEvfULkBQaB+nOE6TGQQ11haeaAWBe8MsKQ2MAkSWdxjW50oAIWNkHO6bPAECbzhf5Fx92rrrjBup10jRemvjXhdstX8kn2g84dYgVXHzkC5yCM91S/X9/Mlgtgu5QE1WXz7KTKjcfPmupfOYFRBMOosw9W8Hd5ZLQr6NoThwQ/kZ6lfvaK7JFZ6UY4GdF1R0Nh1Wz14mAQGk1WdSZKza3oazeFSgn7fRfqFYZrRlo9iaN57mebRDSsvd1fSfeXJJ
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
