---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-wg
  namespace: apps
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBcqp0xAGsF6FEtNMxXw6bKWnYkonkG/rAExyqNwFlYbbya7FVm51BWM4/2YbVRzbk5EqLoS/pWFQaP1VKD6rrX9DVxTVY2raK0098HV9gi/vYM1u5lQH5oS/AHFm1tyiUeA3gZAVlQoJBBXrKw3RLhbjY+7xCN3VKAvnvX7zbzfQzf2Mr0Vaq/k4VtXzbLEwd6u8Di/6kSkh2GNHIs8LRZz5MCYx7JyRpyLwcnwY7t0VoIfEPpGXfW5TK6a9dG1IBdyGZwDSUBVhBPxpTnXK71wj79d9fl3hogd4dFfLsbhwRs/4UWKKLnYcXm6EoGzGdYOf+qz/d93YKf7cifwJk+ejv2FVxqU2nYKMm30LVjdcLvHX6YScPAyrD2/xmzmyUO8gnHtOewgn9iwhIIaWZ36Aykbhr/MbC+5Qs2OjLfgODSbW1EnaW4fLgnoiQ/UIitl6idHfw9oQyp8oGA41m+wn06GYdhoc3RtC5rmzvN2sZkH1FBZbCriyiQT1nL1p/s+6FuSGiWW4U0CmHeKj2v98FL3yn/niL/Alj1FCpDP/xi2SEjYWixlhnyoxtfq41oZDWRPJRI6Haf1NjmwtRbSWl01mLqfkPalspGa4vxHaA5wtAyIN94JCSuL7Y83o57UZvCDE4DrbnvZMeOhEIUA5FilMVGxMa/9J4HsUOD6U7Tk2DudzHCIYRv1LJwhaLOs5sdgk/4kCQ7q8XmJGqsxYB4t9AI1dZeiF3zHpHhieFlf/gH3gs1sNqYHQ==
  template:
    metadata:
      name: gluetun-wg
      namespace: apps
