services:
  gluetun:
    image: qmcgaw/gluetun@sha256:bca4ddb017c25bc37e498a1907f3165371c0eae011cb2d9ea73856ca2d806f2c
    container_name: gluetun
    restart: unless-stopped
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
      - config.env
    volumes:
      - ${DOCKER_DATA_DIR}/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 1m
    profiles:
      - gluetun
      - all

  # Use Gost as a proxy because its better.
  gost:
    image: ginuerzh/gost:latest@sha256:1164471f53b080c5c220e5af8f62a0bb80b914d5012ca7ad1173c79277d4c2eb
    user: "${PUID}:${PGID}"
    container_name: gost
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: service:gluetun
    command: "-L :8080"
    healthcheck:
      test: ["CMD", "pgrep", "gost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    profiles:
      - gluetun
      - all
  
      
