services:
  gluetun:
    image: qmcgaw/gluetun@sha256:c5411925f73f0721b1d6bb2bfd89d6236dc3c66ddf38a1336e45308dc33859f9
    container_name: gluetun
    restart: unless-stopped
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
      - config.env
    volumes:
      - ${DOCKER_DATA_DIR}/gluetun:/gluetun
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 1m
    profiles:
      - gluetun
      - all

  # Use Gost as a proxy because its better.
  gost:
    image: ginuerzh/gost
    user: "${PUID}:${PGID}"
    container_name: gost
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    network_mode: service:gluetun
    command: "-L :8080"
    healthcheck:
      test: ["CMD", "pgrep", "gost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    profiles:
      - gluetun
      - all
  
      
