---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAQBd/2o7vOekYzi1EADxJQcFWkK12kLupiKE46BWRudSi5Rj8Sr7Lbw86Zrzys60aKtZUbowkFU9/epKVuyqVW/ctPZoXCMbNIoM+ks/Lc5X4jhhmzVozDfq4F+li/IbfOQr+lZ0WMli9P8HMaNBD+i8u9EmqdOrPNzHJpnVdoGR94OpLokznOVGcfaITgKI0TpqkpWXFz6Ys7OaWlnkIuOqO/GJ9aAHjsw3h5XpSOtuCwhtXrBbmey16241h3lXqlHGB06DvmQblF3TEqNoyV1r8i3f5jRPfiEAqCwMORJX9Lp5dV7YC0akuVqpoqW4XWNOrTk8GaOu3SBBgEJyvOVxR9qXAhoWj1fGCCB5HTx+cCK2HaKBulhWc/xaDppKYp+CbrpKwE0HKFGccXAT9v6FBEbMtfc+83iDNYdXXET/CkHTP0u0c+A0J8DA4GuzkT1BDmVNpQpxmZJ2ZJnTtzSAdMZCd9JAQ3xB/dVGuqUUeH3Q3nRLwKYAqqvL5LAFP1pvVpD6tFWoZVK4rLH+1faQ9Khf3kk8NGzNOQHXUkRc2z52lwojAGdRWLQR18ZyupWL7WQybF+fC7BaQPR2puoXzHOpAFYX7ys2v+MJZNZWkG3jh7UxhaJ/l3Ll26mnk5uT4s8AbvkbtE0HE0Hf3I0y2EU4HOlUuIi1DU5GLoaVKEVegCBFtuOKHu3CejyA/j2slFidEM0WVwuwJeGSLIAFrS0Xj8fZpZbgUaKZwC8MFvaFAZEr8g
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
