services:
  realdebrid-account-monitor:
    build:
      context: .
    image: realdebrid-account-monitor
    container_name: realdebrid-account-monitor
    env_file:
      - .env
      - config.env
    volumes:
      - ${DOCKER_DATA_DIR}/realdebrid-account-monitor:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    profiles:
      - all
      - realdebrid-account-monitor


