services:
  libremdb:
    container_name: libremdb
    image: ghcr.io/zyachel/libremdb:latest@sha256:9f65a47fe64133045b4cfaa48e5ef73371c55c62b3d5bf42f7584a90dfd1c1ee
    env_file:
      - .env
      - config.env
    depends_on:
      libremdb-redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: 65534:65534
    read_only: true
    tmpfs:
      - /opt/app/.next/cache/:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.libremdb.rule=Host(`${LIBREMDB_HOSTNAME?}`)"
      - "traefik.http.routers.libremdb.entrypoints=websecure"
      - "traefik.http.routers.libremdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.libremdb.middlewares=authelia@docker"
      - "traefik.http.services.libremdb.loadbalancer.server.port=3000"
    profiles:
      - libremdb
      - all

  libremdb-redis:
    mem_limit: 256m
    container_name: libremdb_redis
    image: redis:8.6.3
    # FOR DEBUGGING ONLY
    # ports:
    #   - "6379:6379"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /data:size=10M,mode=0770,uid=65534,gid=65534,noexec,nosuid,nodev
    cap_drop:
      - ALL
    command: redis-server --maxmemory 8mb --maxmemory-policy allkeys-lru --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    profiles:
      - libremdb
      - all