---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: apps
spec:
  encryptedData:
    DB_PASSWORD: AgCyZA5ggyXjmaFrGgIl4u6W0KxsratbVZK9A5crqIOCT4lzyTBVk2BvRhDVOs1MvoUpI/kGgeZP1vYcg0DeoT4X4dAT2FyrUlUuszdQyxHNALF6TXcLCFK/VKMd72FywPxdacLixsz1HH0lHzxPDyVqrF3yhgWqVZ8UdmpwESalK/ef3sUGSYST0qoYAMw2wQgP6emOUuQNz96Ebyb2PGnkKp0thQA4b9MEPnfIT1jlBdiaK02QSMbcKFPDN4/Awicd8ipjwOR+vtlxYqIsG32QafTBFbT/+Pblts2T4g+n9r0Tp5rCKW+l/qAfSyf6dpusdV8hON2sU+whczFv0QVeGC1tCTxrIN0tazaT/oi8NNjUkfzpZOfe+INDQ1E5WBGajf1iU4TFmUN92+vMPGMPG/Odzt0bX1byLmwb423XUapvQXTZAYdcG9d8z4Cqeua8u5QZeVq42cKX46G6fEFzH0mVaoGQhMTmcB3Ru+ZKWuFnrUa1UsdnOvF9hU8ILB3JC2MxbufjGrcdJzCgdD13Qjo0sP3JErcKlsdGmWKtg7te6sXJ7yvJLo2SWY6JoWcSoQoDaflmqcVIdvsDr9pAJX/zjSoruiUqdi8vyQyRrJYcQAmdPyvm12s3ALFMV7MeHbM0hcNxsd9AljYCqxCXD/HC66auiB9mYWAciMFuWlT6RrmmvUtqa7eCKQEtjFrgFeqWJtjrfA==
  template:
    metadata:
      name: immich-secrets
      namespace: apps
