---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: apps
spec:
  encryptedData:
    DB_PASSWORD: AgC1g6z8gqv7YSVo+DuX6+G450ltSuJf2mmo9/UaaEC+oB30Lg0ePKHsmbzsGHZO+Ydg1KLymj6wiCZqerHzL2QOXjTfPkGFu+9KaTz7G8xBh+wM1NA+9ul5T2crrSMiP6smstMJK1vVk6jc+/TpWVj81o/wB2iHskHK2mtSB6FW1CykeiMRzdYPVoCNTWFdvj92n8q5bvG3ItwMH62zHWSe00aNM+ge2hueHoZXXWo56ZQ2t00HtBnNviuSOVyWzbRsP2gJd6Os1V/rqP2Mo5eCaEnb7q/2YO/zb0dKQaDAIukKg0sgPcD0tAB8T6kyvlIHJxeNBLsyoB+DqHr3Y0kwk6oO/ZW8ktPpYtCMMHS4Guirp/1ZFNWtnyg04jFTAnT8vu2XJM1mTaLzYAcF7isfL1HH82tBgdbz9aqjM4jotQywWw6WujAHVlo90YzVgmkRQFY47Q8wh+D5cvQKPHxmuXTySoHh0Zrpbp3clv/vu4SVw/yarmlgCnLUDUMli4z5xX8XkjpmOCr7SUCTWxuscSQn8ZwX1WeVAfHRm2dt7DVcoivgsmzlRou632GLff9CdrEqTigXtgmGmQ07MTcPLi5iULasEnCyEXbFP3DE4jKZSbHhq7P2u51K1sIi1E3zpWJSVsQ4KfgBPfDu167aJWR0smlJulJ2MOilDKl0B4ail7ux+wVALRU8Kg+gEkk4siRflAVY8ws1bdJZxhrEFwM+mP+bZkkd66iOQBoCfsZK/t1FJgGVNWSJwRyCjSk=
  template:
    metadata:
      name: immich-secrets
      namespace: apps
